(*  Title:      Prelude.thy
    ID:         $Id$
    Author:     Florian, TU Muenchen

Base environment for theories generated by the Haskell importer.
*)

theory Prelude
imports Main
begin

class print = type +
  fixes print :: "'a \<Rightarrow> string"

class eq = type +
  fixes eq :: "'a \<Rightarrow> 'a \<Rightarrow> bool"

class num = number_ring + eq + print + abs + sgn

end