#!/bin/bash
#
# Author: Florian Haftmann, TU Muenchen
#
# Building the Haskabelle documentation

## environment

PRG="$(basename "$0")"
HASKABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd ..; pwd)"

## diagnostics

function fail()
{
  echo "$1" >&2
  exit 2
}

## building

cd "$HASKABELLE_HOME/doc-src/Haskabelle"
"$HASKABELLE_HOME/bin/isabelle" make || fail "building documentation sources failed"
make doc || fail "building documentation pdf failed"
