#!/bin/bash
#
# Author: Florian Haftmann, TU Muenchen
#
# Building the Haskabelle documentation
#
# Must be run in an isabelle environment (e.g. via "isabelle env")

## environment

PRG="$(basename "$0")"
HASKABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd ..; pwd)"

## diagnostics

function fail()
{
  echo "$1" >&2
  exit 2
}

## building

cd "$HASKABELLE_HOME/doc-src/Haskabelle"
$ISABELLE_TOOL make clean || fail "building documentation sources failed"
$ISABELLE_TOOL make || fail "building documentation sources failed"
make doc || fail "building documentation pdf failed"
