#!/bin/bash
#
# Author: Florian Haftmann, TU Muenchen
#
# Configuration for automatic Haskabelle test.

ISABELLE_HOME=/home/isatest/isadist/Isabelle
ISABELLE_PATH=/home/isatest/isabelle-at-poly-para-e/heaps
ISABELLE_PROCESS="$ISABELLE_HOME/bin/isabelle-process"
ISABELLE_TOOL="$ISABELLE_HOME/bin/isabelle"
GHC=/usr/local/ldist/bin/ghc

#NOTIFY='kleing@cse.unsw.edu.au tcr@freebits.de haftmann@in.tum.de'
NOTIFY='haftmann@in.tum.de'