#!/bin/bash
#
# Author: Florian Haftmann, TU Muenchen
#
# Run regression with logging and mail failures

## environment

HASKABELLE_HOME="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd ..; pwd)"
cd "$HASKABELLE_HOME"

MAIL=admin/mail-attach

. admin/config

export ISABELLE_DOC_SRC
export ISABELLE_TOOL
export ISABELLE_PROCESS
export GHC
export REPOSITORY
export DIST_HOME

## log

mkdir -p log
LOG=log/haskabelle-$(date +'%Y-%m-%d_%H:%M:%S').log

## run

admin/regression > "$LOG" 2>&1

if [ -n $? ]
then
  MAILTEXT=/tmp/haskabelle-$(date +'%Y-%m-%d_%H:%M:%S').mail

  cat > "$MAILTEXT" <<EOF
Haskabelle test failed.  See attached log.

Have a nice day,
  isatest

EOF

  for RECEIVER in $NOTIFY
  do
    "$MAIL" 'test failed (Haskabelle)' "$RECEIVER" "$MAILTEXT" "$LOG"
  done
  rm "$MAILTEXT"
  
else
  echo Done. >> "$LOG"
fi
